swagger: "2.0"
info:
  version: "0.0.1"
  title: gitlab classroom
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  
  /classes:
      x-swagger-router-controller: classes
      get:
        description: get all classes enrolled
        operationId: listAll
        parameters:
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /classes/{id}:
      x-swagger-router-controller: classes
      get:
        description: get a specific class
        operationId: get
        parameters:
        - name: id
          in: path
          description: class id
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /classes/{id}/assignments:
      x-swagger-router-controller: classes
      get:
        description: get all assignments of a class
        operationId: listAssignments
        parameters:
        - name: id
          in: path
          description: class id
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /classes/{id}/materials:
      x-swagger-router-controller: classes
      get:
        description: get all materials of a class
        operationId: listMaterials
        parameters:
        - name: id
          in: path
          description: class id
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /classes/{id}/members:
      x-swagger-router-controller: classes
      get:
        description: get all members of a class
        operationId: listMembers
        parameters:
        - name: id
          in: path
          description: class id
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /classes/{id}/notifications:
      x-swagger-router-controller: classes
      get:
        description: get all notifications of a class
        operationId: listNotifications
        parameters:
        - name: id
          in: path
          description: class id
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /classes/{id}/activities:
      x-swagger-router-controller: classes
      get:
        description: get all activities of a class
        operationId: listActivities
        parameters:
        - name: id
          in: path
          description: class id
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /assignments:
      x-swagger-router-controller: assignments
      get:
        description: get all assignments involved, ranked by days
        operationId: listAll
        parameters:
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /assignments/{id}:
      x-swagger-router-controller: assignments
      get:
        description: get a specific assignment
        operationId: get
        parameters:
        - name: id
          in: path
          description: assignment id
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /users/{id}:
      x-swagger-router-controller: users
      get:
        description: get a specific user
        operationId: get
        parameters:
        - name: id
          in: path
          description: user id, user "me" get get current user
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /session/login:
      x-swagger-router-controller: session
      get:
        description: Login and set token in cookie
        operationId: login
        parameters:
        - name: username
          in: query
          description: Username or Email 
          required: true
          type: string
        - name: password
          in: query
          description: Password of user
          required: true
          type: string
        - name: Cookie
          in: header
          description: token in cookie
          type: string
          required: true
        responses:
          "200":
            description: Success
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  DefaultResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
